export const products = [
    {
        id: "1",
        name: "Brazilian Body Wave Wig",
        description:
            "Premium quality Brazilian body wave wig with natural hairline. Made with 100% human hair, this wig offers a natural look and feel. The body wave pattern adds volume and movement to your style.",
        price: 45000,
        originalPrice: 55000,
        discount: 18,
        category: "Wigs",
        image: "/images/wig-1.jpg",
        images: ["/images/wig-1.jpg", "/images/wig-1-2.jpg", "/images/wig-1-3.jpg"],
        features: [
            "100% Human Hair",
            "Pre-plucked hairline",
            "Medium density",
            "Natural black color",
            "Body wave texture",
            "Lace frontal",
            "Length: 18 inches",
        ],
        stock: 12,
        rating: 4.8,
        reviews: 24,
        tags: ["body wave", "brazilian", "human hair", "lace front"],
    },
    {
        id: "2",
        name: "Straight Human Hair Wig",
        description:
            "Silky straight human hair wig with transparent lace. This premium wig features a pre-plucked hairline and baby hairs for a natural look. The straight texture provides a sleek, elegant style.",
        price: 52000,
        originalPrice: 60000,
        discount: 13,
        category: "Wigs",
        image: "/images/wig-2.jpg",
        images: ["/images/wig-2.jpg", "/images/wig-2-2.jpg", "/images/wig-2-3.jpg"],
        features: [
            "100% Human Hair",
            "Transparent HD lace",
            "Pre-plucked with baby hairs",
            "High density",
            "Natural black color",
            "Straight texture",
            "Length: 20 inches",
        ],
        stock: 8,
        rating: 4.9,
        reviews: 32,
        tags: ["straight", "human hair", "transparent lace", "HD lace"],
    },
    {
        id: "3",
        name: "Curly Synthetic Wig",
        description:
            "Affordable curly synthetic wig with natural look. This wig features heat-resistant fibers that can be styled with low heat. The curly pattern adds volume and bounce to your style.",
        price: 18000,
        originalPrice: 22000,
        discount: 18,
        category: "Wigs",
        image: "/images/wig-3.jpg",
        images: ["/images/wig-3.jpg", "/images/wig-3-2.jpg", "/images/wig-3-3.jpg"],
        features: [
            "Premium Synthetic Fiber",
            "Heat resistant up to 180°C",
            "Medium density",
            "Natural black color",
            "Curly texture",
            "Length: 16 inches",
        ],
        stock: 15,
        rating: 4.5,
        reviews: 18,
        tags: ["curly", "synthetic", "affordable", "heat resistant"],
    },
    {
        id: "4",
        name: "Lace Frontal Closure",
        description:
            "13x4 lace frontal closure with pre-plucked hairline. This frontal closure can be used to create a custom wig or installed directly for a natural-looking hairline. Made with 100% human hair.",
        price: 28000,
        originalPrice: 35000,
        discount: 20,
        category: "Frontals",
        image: "/images/frontal-1.jpg",
        images: ["/images/frontal-1.jpg", "/images/frontal-1-2.jpg", "/images/frontal-1-3.jpg"],
        features: [
            "100% Human Hair",
            "13x4 lace frontal",
            "Pre-plucked hairline",
            "Medium density",
            "Natural black color",
            "Can be bleached and dyed",
        ],
        stock: 10,
        rating: 4.7,
        reviews: 15,
        tags: ["frontal", "closure", "13x4", "human hair"],
    },
    {
        id: "5",
        name: "360 Lace Frontal",
        description:
            "360 lace frontal with pre-plucked hairline and baby hairs. This frontal provides coverage around the entire perimeter of the head for versatile styling options. Made with 100% human hair.",
        price: 38000,
        originalPrice: 45000,
        discount: 16,
        category: "Frontals",
        image: "/images/frontal-2.jpg",
        images: ["/images/frontal-2.jpg", "/images/frontal-2-2.jpg", "/images/frontal-2-3.jpg"],
        features: [
            "100% Human Hair",
            "360 lace frontal",
            "Pre-plucked with baby hairs",
            "Medium density",
            "Natural black color",
            "Can be bleached and dyed",
        ],
        stock: 6,
        rating: 4.9,
        reviews: 12,
        tags: ["360 frontal", "human hair", "pre-plucked"],
    },
    {
        id: "6",
        name: "Wig Cap",
        description:
            "Stretchable wig cap for secure wig installation. This breathable mesh cap helps keep your natural hair flat and provides a base for wig application. One size fits most.",
        price: 1500,
        originalPrice: null,
        discount: 0,
        category: "Tools",
        image: "/images/tool-1.jpg",
        images: ["/images/tool-1.jpg", "/images/tool-1-2.jpg"],
        features: [
            "Breathable mesh material",
            "Stretchable for comfortable fit",
            "Beige color",
            "One size fits most",
            "Pack of 2",
        ],
        stock: 50,
        rating: 4.3,
        reviews: 28,
        tags: ["wig cap", "mesh cap", "accessories"],
    },
    {
        id: "7",
        name: "Wig Glue",
        description:
            "Professional-grade wig adhesive for secure installation. This waterproof formula provides a strong hold that lasts for days. Suitable for lace front wigs and frontals.",
        price: 5000,
        originalPrice: 6000,
        discount: 17,
        category: "Tools",
        image: "/images/tool-2.jpg",
        images: ["/images/tool-2.jpg", "/images/tool-2-2.jpg"],
        features: [
            "Professional-grade adhesive",
            "Waterproof formula",
            "Long-lasting hold",
            "Easy to remove",
            "Dermatologically tested",
            "2 oz bottle",
        ],
        stock: 25,
        rating: 4.6,
        reviews: 22,
        tags: ["wig glue", "adhesive", "waterproof"],
    },
    {
        id: "8",
        name: "Lace Tint Spray",
        description:
            "Lace tint spray for seamless lace blending. This spray helps match the lace of your wig or frontal to your skin tone for a natural-looking hairline. Available in multiple shades.",
        price: 4500,
        originalPrice: 5500,
        discount: 18,
        category: "Tools",
        image: "/images/tool-3.jpg",
        images: ["/images/tool-3.jpg", "/images/tool-3-2.jpg"],
        features: [
            "Easy application spray",
            "Quick-drying formula",
            "Available in multiple shades",
            "Waterproof",
            "Long-lasting",
            "4 oz bottle",
        ],
        stock: 18,
        rating: 4.4,
        reviews: 16,
        tags: ["lace tint", "spray", "blending"],
    },
    {
        id: "9",
        name: "Deep Wave Wig",
        description:
            "Luxurious deep wave wig with natural hairline. Made with 100% human hair, this wig features a deep wave pattern that adds texture and volume. Perfect for a glamorous look.",
        price: 48000,
        originalPrice: 58000,
        discount: 17,
        category: "Wigs",
        image: "/images/wig-4.jpg",
        images: ["/images/wig-4.jpg", "/images/wig-4-2.jpg", "/images/wig-4-3.jpg"],
        features: [
            "100% Human Hair",
            "Pre-plucked hairline",
            "High density",
            "Natural black color",
            "Deep wave texture",
            "Lace frontal",
            "Length: 22 inches",
        ],
        stock: 7,
        rating: 4.8,
        reviews: 19,
        tags: ["deep wave", "human hair", "lace front"],
    },
    {
        id: "10",
        name: "Bob Style Wig",
        description:
            "Chic bob style wig with middle part. This wig features a sleek, straight bob cut that falls just above the shoulders. Made with 100% human hair for a natural look and feel.",
        price: 35000,
        originalPrice: 42000,
        discount: 17,
        category: "Wigs",
        image: "/images/wig-5.jpg",
        images: ["/images/wig-5.jpg", "/images/wig-5-2.jpg", "/images/wig-5-3.jpg"],
        features: [
            "100% Human Hair",
            "Pre-plucked hairline",
            "Medium density",
            "Natural black color",
            "Straight texture",
            "Bob cut with middle part",
            "Length: 12 inches",
        ],
        stock: 9,
        rating: 4.7,
        reviews: 21,
        tags: ["bob", "short", "human hair", "straight"],
    },
    {
        id: "11",
        name: "Blonde Highlight Wig",
        description:
            "Stunning blonde highlight wig with dark roots. This wig features a blend of blonde highlights on a darker base for a dimensional look. Made with 100% human hair that can be styled as desired.",
        price: 55000,
        originalPrice: 65000,
        discount: 15,
        category: "Wigs",
        image: "/images/wig-6.jpg",
        images: ["/images/wig-6.jpg", "/images/wig-6-2.jpg", "/images/wig-6-3.jpg"],
        features: [
            "100% Human Hair",
            "Pre-plucked hairline",
            "High density",
            "Blonde highlights with dark roots",
            "Wavy texture",
            "Lace frontal",
            "Length: 18 inches",
        ],
        stock: 5,
        rating: 4.9,
        reviews: 17,
        tags: ["blonde", "highlights", "human hair", "wavy"],
    },
    {
        id: "12",
        name: "HD Lace Closure",
        description:
            "Premium HD lace closure for an invisible hairline. This 5x5 closure features transparent HD lace that blends seamlessly with your skin. Made with 100% human hair that can be bleached and styled.",
        price: 25000,
        originalPrice: 30000,
        discount: 17,
        category: "Frontals",
        image: "/images/frontal-3.jpg",
        images: ["/images/frontal-3.jpg", "/images/frontal-3-2.jpg", "/images/frontal-3-3.jpg"],
        features: [
            "100% Human Hair",
            "5x5 HD lace closure",
            "Transparent lace",
            "Pre-plucked hairline",
            "Medium density",
            "Natural black color",
            "Can be bleached and dyed",
        ],
        stock: 11,
        rating: 4.8,
        reviews: 14,
        tags: ["HD lace", "closure", "5x5", "human hair"],
    },
]

