import type { Product } from "./types"

export const featuredWigs: Product[] = [
  {
    id: "wig-1",
    name: "Brazilian Body Wave Wig",
    description: "100% human hair body wave wig with lace frontal closure.",
    price: 45000,
    originalPrice: 55000,
    discount: 18,
    image: "/placeholder.svg?height=400&width=300",
    category: "wigs",
    inStock: true,
    rating: 4.8,
    reviews: 24,
    features: ["100% human hair", "Pre-plucked hairline", "Bleached knots", "Medium brown lace"],
  },
  {
    id: "wig-2",
    name: "Straight Human Hair Wig",
    description: "Premium straight human hair wig with 13x4 lace frontal.",
    price: 52000,
    originalPrice: 60000,
    discount: 13,
    image: "/placeholder.svg?height=400&width=300",
    category: "wigs",
    inStock: true,
    rating: 4.7,
    reviews: 18,
    features: ["100% human hair", "Pre-plucked hairline", "Bleached knots", "HD lace"],
  },
  {
    id: "wig-3",
    name: "Curly Bob Wig",
    description: "Short curly bob wig with natural hairline and deep parting.",
    price: 38000,
    originalPrice: 42000,
    discount: 10,
    image: "/placeholder.svg?height=400&width=300",
    category: "wigs",
    inStock: true,
    rating: 4.6,
    reviews: 15,
    features: ["100% human hair", "Pre-plucked hairline", "Bleached knots", "Glueless cap"],
  },
  {
    id: "wig-4",
    name: "Kinky Curly Full Lace Wig",
    description: "Natural kinky curly pattern with full lace for versatile styling.",
    price: 65000,
    originalPrice: 75000,
    discount: 13,
    image: "/placeholder.svg?height=400&width=300",
    category: "wigs",
    inStock: true,
    rating: 4.9,
    reviews: 32,
    features: ["100% human hair", "Full lace", "Pre-plucked hairline", "Bleached knots"],
  },
]

export const featuredFrontals: Product[] = [
  {
    id: "frontal-1",
    name: "13x4 HD Lace Frontal",
    description: "High-definition transparent lace frontal with pre-plucked hairline.",
    price: 25000,
    originalPrice: 30000,
    discount: 17,
    image: "/placeholder.svg?height=400&width=300",
    category: "frontals",
    inStock: true,
    rating: 4.7,
    reviews: 14,
    features: ["13x4 HD lace", "Pre-plucked hairline", "Bleached knots", "Natural hairline"],
  },
  {
    id: "frontal-2",
    name: "360 Lace Frontal",
    description: "360-degree lace frontal for full hairline coverage and versatile styling.",
    price: 35000,
    originalPrice: 40000,
    discount: 13,
    image: "/placeholder.svg?height=400&width=300",
    category: "frontals",
    inStock: true,
    rating: 4.8,
    reviews: 22,
    features: ["360-degree lace", "Pre-plucked hairline", "Bleached knots", "Baby hair"],
  },
  {
    id: "frontal-3",
    name: "Transparent Swiss Lace Frontal",
    description: "Premium Swiss lace frontal with invisible hairline.",
    price: 28000,
    originalPrice: 32000,
    discount: 13,
    image: "/placeholder.svg?height=400&width=300",
    category: "frontals",
    inStock: true,
    rating: 4.6,
    reviews: 17,
    features: ["Swiss lace", "Pre-plucked hairline", "Bleached knots", "Transparent lace"],
  },
  {
    id: "frontal-4",
    name: "Kinky Straight Lace Frontal",
    description: "Natural kinky straight texture with 13x6 lace frontal.",
    price: 30000,
    originalPrice: 35000,
    discount: 14,
    image: "/placeholder.svg?height=400&width=300",
    category: "frontals",
    inStock: true,
    rating: 4.7,
    reviews: 19,
    features: ["13x6 lace", "Pre-plucked hairline", "Bleached knots", "Natural texture"],
  },
]

export const featuredTools: Product[] = [
  {
    id: "tool-1",
    name: "Professional Wig Stand",
    description: "Sturdy wig stand for styling and maintaining your wigs.",
    price: 5000,
    originalPrice: 6000,
    discount: 17,
    image: "/placeholder.svg?height=400&width=300",
    category: "tools",
    inStock: true,
    rating: 4.5,
    reviews: 12,
    features: ["Adjustable height", "Stable base", "Lightweight", "Portable"],
  },
  {
    id: "tool-2",
    name: "Lace Tint Spray",
    description: "Color-matching spray to blend lace with your skin tone.",
    price: 3500,
    originalPrice: 4000,
    discount: 13,
    image: "/placeholder.svg?height=400&width=300",
    category: "tools",
    inStock: true,
    rating: 4.6,
    reviews: 15,
    features: ["Multiple shades", "Long-lasting", "Water-resistant", "Easy application"],
  },
  {
    id: "tool-3",
    name: "Wig Adhesive Kit",
    description: "Complete kit for secure wig installation.",
    price: 8000,
    originalPrice: 9500,
    discount: 16,
    image: "/placeholder.svg?height=400&width=300",
    category: "tools",
    inStock: true,
    rating: 4.8,
    reviews: 24,
    features: ["Strong hold", "Waterproof", "Includes remover", "Skin-friendly"],
  },
  {
    id: "tool-4",
    name: "Edge Control Brush Set",
    description: "Professional brush set for laying edges and styling baby hairs.",
    price: 2500,
    originalPrice: 3000,
    discount: 17,
    image: "/placeholder.svg?height=400&width=300",
    category: "tools",
    inStock: true,
    rating: 4.7,
    reviews: 18,
    features: ["Multiple brush sizes", "Ergonomic handle", "Precision tip", "Durable bristles"],
  },
]

